Repository eBay/skin, pull requests merged in 2018-04, with the labels that each got.

#166 Remove deprecated classes, mixins and variables
  dist/button/ds4/button.css
  dist/less/variables-common.less
  dist/menu/ds4/menu.css
  dist/notice/ds6/notice.css
  dist/utility/ds4/utility.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/skin.css
  src/less/button/ds4/button-base.less
  src/less/less/variables-common.less
  src/less/marketsans/marketsans.less
  src/less/menu/ds4/menu-base.less
  src/less/menu/ds4/menu-mixins.less
  src/less/menu/ds4/menu.less
  src/less/notice/ds6/notice-base.less
  src/less/utility/ds4/utility.less
Labels: type: tech debt

#167 Docs: added modal behaviour to dialog examples
  docs/_includes/ds6/dialog.html
  docs/src/js/ds6/main.js
  docs/static/ds6/docs.js
  package.json
  yarn.lock
Labels: aspect: website, type: enhancement

#171 Fix for small screens; Fix headers padding;
  docs/src/less/ds6/index.less
  docs/static/ds6/docs.css
Labels: aspect: website
