Repository eBay/skin, pull requests merged in 2018-10, with the labels that each got.

#402 Added badges for skin
  badge.browser.json
  browser.json
  dist/badge/ds4/badge.css
  dist/badge/ds6/badge.css
  dist/less/ds6/variables.less
  docs/_includes/common/badge.html
  docs/_layouts/ds4/default.html
  docs/_layouts/ds6/default.html
  docs/ds6/index.html
  docs/index.html
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/docs.js
  docs/static/ds6/skin.css
  docs/test/badge/ds4/index.html
  docs/test/badge/ds6/index.html
  docs/test/index.html
  gh.browser.json
  patch.diff
  src/less/badge/base/badge.less
  src/less/badge/ds4/badge.less
  src/less/badge/ds6/badge-mixin.less
  src/less/badge/ds6/badge.less
  src/less/bundles/skin/ds4/skin.less
  src/less/bundles/skin/ds6/skin.less
  src/less/less/ds6/variables.less
Labels: squash: yes please

#407 Editable combobox
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  dist/dropdown/ds4/dropdown.css
  dist/dropdown/ds6/dropdown.css
  dist/listbox/ds4/listbox.css
  dist/listbox/ds6/listbox.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  docs/_includes/common/combobox.html
  docs/_includes/common/listbox.html
  docs/_includes/ds4/combobox-custom.html
  docs/_includes/ds6/combobox-custom.html
  docs/src/js/ds4/main.js
  docs/src/js/ds6/main.js
  docs/static/ds4/docs.js
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/docs.js
  docs/static/ds6/skin.css
  docs/test/combobox/ds4/index.html
  docs/test/combobox/ds6/index.html
  src/less/combobox/base/combobox.less
  src/less/dropdown/base/dropdown.less
  src/less/dropdown/ds6/dropdown.less
Labels: squash: yes please

#409 Fix for combobox icon stretching
  dist/combobox/ds6/combobox.css
  docs/static/ds6/skin.css
  src/less/combobox/ds6/combobox.less
Labels: squash: yes please

#410 Website: final menu normalization
  docs/_includes/common/menu.html
  docs/_includes/ds4/menu-custom.html
  docs/_includes/ds6/menu-custom.html
  docs/ds4.browser.json
  docs/src/js/ds4/main.js
  docs/src/js/ds6/main.js
  docs/static/ds4/docs.js
  docs/static/ds6/docs.js
Labels: squash: yes please

#404 376 color update to the new brand pallette
  dist/badge/ds6/badge.css
  dist/breadcrumb/ds6/breadcrumb.css
  dist/button/ds6/button.css
  dist/checkbox/ds6/checkbox.css
  dist/color/ds6/color.css
  dist/combobox/ds6/combobox.css
  dist/dialog/ds6/dialog.css
  dist/dropdown/ds6/dropdown.css
  dist/field/ds6/field.css
  dist/global/ds6/global.css
  dist/icon/ds6/icon.css
  dist/label/ds6/label.css
  dist/less/ds6/mixins.less
  dist/less/ds6/variables.less
  dist/link/ds6/link.css
  dist/listbox/ds6/listbox.css
  dist/menu/ds6/menu.css
  dist/notice/ds6/notice.css
  dist/pagination/ds6/pagination.css
  dist/radio/ds6/radio.css
  dist/select/ds6/select.css
  dist/switch/ds6/switch.css
  dist/tab/ds6/tab.css
  dist/textbox/ds6/textbox.css
  dist/tooltip/ds6/tooltip.css
  dist/typography/ds6/typography.css
  docs/_includes/ds6/button-cta.html
  docs/_includes/ds6/less.html
  docs/src/less/ds6/index.less
  docs/static/ds6/docs.css
  docs/static/ds6/skin.css
  src/less/breadcrumb/ds6/breadcrumb.less
  src/less/button/ds6/button-cta.less
  src/less/button/ds6/button-primary.less
  src/less/button/ds6/button-regular.less
  src/less/button/ds6/button-secondary.less
  src/less/combobox/ds6/combobox.less
  src/less/dialog/ds6/dialog.less
  src/less/dropdown/ds6/dropdown.less
  src/less/label/ds6/label-base.less
  src/less/less/ds6/mixins.less
  src/less/less/ds6/variables.less
  src/less/link/ds6/link-base.less
  src/less/notice/ds6/notice-base.less
  src/less/select/ds6/select.less
  src/less/switch/ds6/switch.less
  src/less/tab/ds6/tab.less
  src/less/textbox/ds6/textbox-mixins.less
  src/less/textbox/ds6/textbox.less
  src/less/tooltip/ds6/tooltip.less
  src/less/typography/ds6/typography-base.less
Labels: squash: yes please

#417 Tooltip rework (part 1)
  dist/notice/ds4/notice.css
  dist/notice/ds6/notice.css
  docs/_includes/common/notice.html
  docs/_includes/common/tooltip.html
  docs/_includes/ds4/notice-custom.html
  docs/_includes/ds4/tooltip-custom.html
  docs/_includes/ds6/tooltip-custom.html
  docs/_includes/ds6/tooltip.html
  docs/_layouts/ds4/default.html
  docs/ds6/index.html
  docs/index.html
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/skin.css
  src/less/bundles/skin/ds4/skin.less
  src/less/notice/base/notice.less
  src/less/notice/ds4/notice-base.less
  src/less/notice/ds4/notice-mixins.less
  src/less/notice/ds4/notice-tooltip.less
  src/less/notice/ds4/notice.less
  src/less/notice/ds6/notice-base.less
  src/less/tooltip/ds4/tooltip.less
  tooltip.browser.json
Labels: squash: no thanks

#418 Adding color module for DS4
  color.browser.json
  dist/color/ds4/color.css
  src/less/color/ds4/color-base.less
  src/less/color/ds4/color.less
Labels: squash: yes please

#416 Adding missing .background-icon-base mixin;
  dist/notice/ds4/notice.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  src/less/notice/ds4/notice-base.less
Labels: squash: yes please

#420 6.0.5
  dist/notice/ds4/notice.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  package.json
  src/less/notice/ds4/notice-base.less
Labels: squash: no thanks

#422 Build: Adding npm version hook to pick up generated files;
  package.json
Labels: aspect: build, squash: yes please

#427 Fix primary button a11y issue
  dist/button/ds4/button.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  src/less/button/ds4/button-primary.less
Labels: squash: yes please

#425 Website: removed jQuery and all references
  docs/_includes/ds4/card.html
  docs/_includes/ds4/notice-custom.html
  docs/_layouts/ds4/default.html
  docs/ds4.browser.json
  docs/ds6.browser.json
  docs/src/js/base/main.js
  docs/src/js/base/transition.js
  docs/src/js/base/util.js
  docs/src/js/ds4/main.js
  docs/src/js/ds6/main.js
  docs/src/less/ds4/index.less
  docs/static/ds4/docs.css
  docs/static/ds4/docs.js
  docs/static/ds6/docs.js
  package.json
  yarn.lock
Labels: squash: yes please

#429 Tooltip: holding back DS6 tooltip from this release
  dist/less/ds4/variables.less
  dist/tooltip/ds4/tooltip.css
  docs/_layouts/ds6/default.html
  docs/ds6/index.html
  docs/src/js/ds4/main.js
  docs/src/js/ds6/main.js
  docs/static/ds4/docs.js
  docs/static/ds6/docs.js
  docs/static/ds6/skin.css
  docs/test/index.html
  docs/test/notice/ds4/flyout-notice.html
  src/less/bundles/skin/ds6/skin.less
  tooltip.browser.json
Labels: squash: yes please

#433 432 color docs fixes
  docs/_includes/ds6/button-cta.html
  docs/src/less/ds6/index.less
  docs/static/ds6/docs.css
Labels: squash: yes please

#437 Merge v6.0.5 patch commits into 7.0.0 branch
  dist/grid/ds4/grid-full.css
  dist/notice/ds4/notice.css
  docs/_includes/ds4/cdn.html
  docs/_includes/ds4/grid.html
  docs/_includes/ds6/install.html
  docs/static/ds4/docs.js
  docs/static/ds4/grid-full.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin-large.css
  docs/static/ds4/skin.css
  docs/static/ds6/docs.js
  docs/static/ds6/skin.css
  package.json
  src/less/notice/ds4/notice-base.less
Labels: squash: no thanks

#438 Website: removed DS6 feedback icon references
  docs/_includes/ds6/svg.html
Labels: squash: yes please

#439 Badge: some refactoring of classes based on feedback
  dist/actionable/ds4/actionable.css
  dist/actionable/ds6/actionable.css
  dist/badge/ds4/badge.css
  dist/badge/ds6/badge.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  docs/_includes/common/badge.html
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/skin.css
  docs/test/badge/ds4/index.html
  docs/test/badge/ds6/index.html
  src/less/actionable/ds4/actionable-base.less
  src/less/actionable/ds6/actionable.less
  src/less/badge/base/badge.less
  src/less/badge/ds4/badge.less
  src/less/badge/ds6/badge.less
  src/less/bundles/skin/ds6/skin.less
  src/less/menu/base/menu.less
Labels: squash: yes please

#442 Merge 6.1.0 badge refactoring into 7.0.0
  dist/actionable/ds4/actionable.css
  dist/actionable/ds6/actionable.css
  dist/badge/ds4/badge.css
  dist/badge/ds6/badge.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  docs/_includes/common/badge.html
  docs/_includes/ds6/svg.html
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin.css
  docs/static/ds6/skin.css
  docs/test/badge/ds4/index.html
  docs/test/badge/ds6/index.html
  src/less/actionable/ds4/actionable-base.less
  src/less/actionable/ds6/actionable.less
  src/less/badge/base/badge.less
  src/less/badge/ds4/badge.less
  src/less/badge/ds6/badge.less
  src/less/bundles/skin/ds6/skin.less
  src/less/menu/base/menu.less
Labels: squash: no thanks

#444 Merge 6.1.0-prerebase into 7.0.0
  CONTRIBUTING.md
  dist/grid/ds4/grid-full.css
  docs/static/ds4/docs.js
  docs/static/ds4/grid-full.css
  docs/static/ds4/skin-full.css
  docs/static/ds4/skin-large.css
  docs/static/ds4/skin.css
  docs/static/ds6/docs.js
  docs/static/ds6/skin.css
  package.json
Labels: squash: no thanks
