Repository eBay/skin, pull requests merged in 2019-05, with the labels that each got.

#620 CSS variables refactor (2)
  dist/field/ds4/field.css
  dist/field/ds6/field.css
  dist/label/ds4/label.css
  dist/label/ds6/label.css
  dist/less/mixins-common.less
  dist/link/ds4/link.css
  dist/link/ds6/link.css
  dist/radio/ds4/radio.css
  dist/radio/ds6/radio.css
  dist/select/ds4/select.css
  dist/select/ds6/select.css
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/field/base/field.less
  src/less/field/ds4/field.less
  src/less/field/ds6/field.less
  src/less/label/base/label.less
  src/less/label/ds4/label.less
  src/less/label/ds6/label.less
  src/less/link/base/link.less
  src/less/link/ds4/link.less
  src/less/link/ds6/link.less
  src/less/radio/base/radio.less
  src/less/radio/ds4/radio.less
  src/less/radio/ds6/radio.less
  src/less/select/base/select.less
  src/less/select/ds4/select.less
  src/less/select/ds6/select.less
Labels: squash: no thanks

#613 Details expander
  browser.json
  details.browser.json
  details.less
  details[skin-ds6].less
  dist/details/ds4/details.css
  dist/details/ds6/details.css
  dist/less/ds4/mixins.less
  dist/less/ds4/variables.less
  dist/less/ds6/mixins.less
  dist/less/ds6/variables.less
  docs/_includes/common/details.html
  docs/_includes/common/install.html
  docs/_layouts/ds4/default.html
  docs/_layouts/ds6/default.html
  docs/ds4.browser.json
  docs/ds6.browser.json
  docs/ds6/index.html
  docs/index.html
  docs/static/ds4/docs.min.css
  docs/static/ds4/docs.min.js
  docs/static/ds4/skin.min.css
  docs/static/ds6/docs.min.css
  docs/static/ds6/docs.min.js
  docs/static/ds6/skin.min.css
  index.browser.json
  package.json
  src/less/bundles/skin/ds4/skin.less
  src/less/bundles/skin/ds6/skin.less
  src/less/details/base/details.less
  src/less/details/ds4/details.less
  src/less/details/ds6/details.less
  src/less/less/ds4/mixins.less
  src/less/less/ds4/variables.less
  src/less/less/ds6/mixins.less
  src/less/less/ds6/variables.less
  yarn.lock
Labels: module: details, squash: yes please

#621 Website: added nodelist-foreach-polyfill
  docs/ds4.browser.json
  docs/ds6.browser.json
  docs/src/js/base/main.js
  docs/src/js/base/util.js
  docs/static/ds4/docs.min.js
  docs/static/ds6/docs.min.js
  package.json
Labels: squash: yes please
