Repository eBay/skin, pull requests merged in 2019-12, with the labels that each got.

#941 Filter Menu: removed background SVG support #908
  dist/filter-menu-button/ds4/filter-menu-button.css
  dist/filter-menu-button/ds6/filter-menu-button.css
  dist/filter-menu/ds4/filter-menu.css
  dist/filter-menu/ds6/filter-menu.css
  docs/_includes/common/expand-button.html
  docs/_includes/common/filter-menu-button.html
  docs/_includes/common/filter-menu.html
  docs/_includes/tests/filter-menu-button.html
  docs/_includes/tests/filter-menu.html
  docs/src/js/base/main.js
  docs/static/ds4/docs.min.js
  docs/static/ds4/skin.min.css
  docs/static/ds6/docs.min.js
  docs/static/ds6/skin.min.css
  src/less/filter-menu-button/base/filter-menu-button.less
  src/less/filter-menu/base/filter-menu.less
Labels: squash: yes please

#949 Pagination: removed background SVG support #908
  CONTRIBUTING.md
  dist/breadcrumb/ds4/breadcrumb.css
  dist/breadcrumb/ds6/breadcrumb.css
  dist/carousel/ds4/carousel.css
  dist/carousel/ds6/carousel.css
  dist/icon/foreground/ds4/foreground.css
  dist/icon/foreground/ds6/foreground.css
  dist/mixins/layout/layout-mixins.less
  dist/notice/ds4/notice.css
  dist/notice/ds6/notice.css
  dist/pagination/ds4/pagination.css
  dist/pagination/ds6/pagination.css
  docs/_includes/common/pagination.html
  docs/_includes/tests/breadcrumb.html
  docs/_includes/tests/notice-inline.html
  docs/_includes/tests/notice-page.html
  docs/_includes/tests/notice-section.html
  docs/_includes/tests/pagination.html
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/breadcrumb/base/breadcrumb.less
  src/less/carousel/base/carousel.less
  src/less/icon/foreground/base/foreground.less
  src/less/mixins/layout/layout-mixins.less
  src/less/mixins/pagination/base/pagination-mixins.less
  src/less/mixins/pagination/ds4/pagination-mixins.less
  src/less/mixins/pagination/ds6/pagination-mixins.less
  src/less/notice/base/notice.less
  src/less/pagination/base/pagination.less
  src/less/pagination/ds4/pagination.less
  src/less/pagination/ds6/pagination.less
Labels: squash: yes please

#956 Icon: add missing attention-small icon #954
  dist/icon-small/foreground/ds6/foreground.css
  dist/icon/foreground/ds6/foreground.css
  dist/svg/ds6/icons.svg
  dist/variables/ds6/base64-variables.less
  dist/variables/ds6/icon-variables.less
  docs/_includes/ds6/symbols.html
  docs/static/ds6/skin.min.css
  src/less/icon-small/foreground/ds6/foreground.less
  src/less/icon/foreground/ds6/foreground.less
  src/less/variables/ds6/base64-variables.less
  src/less/variables/ds6/icon-variables.less
  src/svg/ds6/icons.svg
Labels: squash: yes please

#960 Removed duplicate search icon
  dist/svg/ds4/icons.svg
  dist/variables/ds4/base64-variables.less
  docs/_includes/ds4/symbols.html
  src/less/variables/ds4/base64-variables.less
  src/svg/ds4/icons.svg
Labels: module: icon

#962 Split up hover and focus within rule for ie/edge
  dist/carousel/ds4/carousel.css
  dist/carousel/ds6/carousel.css
  dist/mixins/carousel/base/carousel-mixins.less
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/mixins/carousel/base/carousel-mixins.less
Labels: module: carousel
