Repository eBay/skin, pull requests merged in 2019-07, with the labels that each got.

#673 Add back top level import of all skin modules
  browser.json
Labels: squash: yes please

#674 Add back top level import of all skin modules
  browser.json
Labels: module: all, squash: no thanks

#677 Added browser.json into icons directory
  icon/browser.json
Labels: design system: DS6, module: icon, type: bug

#686 Added flex: 1 0 auto in order to support IE11.
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  dist/dropdown/ds4/dropdown.css
  dist/dropdown/ds6/dropdown.css
  dist/listbox/ds4/listbox.css
  dist/listbox/ds6/listbox.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/dropdown/base/dropdown.less
Labels: aspect: IE11, module: combobox, module: listbox, module: menu, type: bug

#688 Disallow font zooming on iOS;
  dist/global/ds4/global.css
  dist/global/ds6/global.css
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/global/ds4/global.less
  src/less/global/ds6/global.less
Labels: module: combobox, module: menu, squash: yes please

#691 Added 16px size on infotip button
  dist/tooltip/ds4/tooltip.css
  docs/static/ds4/skin.min.css
  src/less/tooltip/ds4/tooltip.less
Labels: module: icon, module: tooltip

#692 Added display:blocks to spans in tooltip/infotip
  dist/tooltip/ds4/tooltip.css
  dist/tooltip/ds6/tooltip.css
  docs/_includes/common/tooltip.html
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/tooltip/base/tooltip.less
Labels: module: tooltip, type: bug

#694 Carousel: leverage margin-collapse (#680)
  dist/carousel/ds4/carousel.css
  dist/carousel/ds6/carousel.css
  docs/_includes/common/carousel.html
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/carousel/base/carousel.less
Labels: squash: yes please

#706 Icon: normalized DS4 and DS6 styles to base file
  dist/icon/background/ds4/background.css
  dist/icon/background/ds6/background.css
  dist/icon/common/ds4/common.css
  dist/icon/foreground/ds4/foreground.css
  dist/icon/foreground/ds6/foreground.css
  dist/less/mixins-common.less
  docs/static/ds4/skin-base64.min.css
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin-base64.min.css
  docs/static/ds6/skin.min.css
  docs/test/icon/ds4/icon-core.html
  docs/test/icon/ds4/icon-misc.html
  docs/test/icon/ds4/icon-non-critical.html
  docs/test/icon/ds4/icon-null.html
  gulpfile.js
  src/less/icon/background/base/background.less
  src/less/icon/background/ds4/background.less
  src/less/icon/background/ds6/background.less
  src/less/icon/foreground/base/foreground.less
  src/less/icon/foreground/ds4/foreground.less
  src/less/icon/foreground/ds6/foreground.less
  src/less/less/mixins-common.less
Labels: blocking: yes, squash: yes please

#704 Top level relative dependency paths
  browser.json
  combo.browser.json
  core.browser.json
  form.browser.json
  icon.browser.json
  index.browser.json
Labels: squash: yes please

#714 Pill module
  browser.json
  dist/button/ds4/button.css
  dist/button/ds6/button.css
  dist/pill/ds4/pill.css
  dist/pill/ds6/pill.css
  docs/_includes/common/button.html
  docs/_includes/common/pill.html
  docs/_layouts/ds4/default.html
  docs/_layouts/ds6/default.html
  docs/ds6/index.html
  docs/index.html
  docs/static/ds4/skin.min.css
  docs/static/ds4/test.css
  docs/static/ds6/skin.min.css
  docs/static/hero.jpg
  docs/static/iphone.jpg
  docs/static/skin-graphic.png
  pill.browser.json
  pill.less
  pill[skin-ds6].less
  src/less/bundles/skin/ds4/skin.less
  src/less/bundles/skin/ds6/skin.less
  src/less/button/base/button-pill.less
  src/less/button/base/button.less
  src/less/button/ds4/button-sizes.less
  src/less/button/ds4/button.less
  src/less/button/ds6/button-sizes.less
  src/less/button/ds6/button.less
  src/less/gh/ds6/gh-mixins.less
  src/less/mixins/button/base/button-mixins.less
  src/less/mixins/button/ds4/button-mixins.less
  src/less/mixins/button/ds6/button-mixins.less
  src/less/pill/base/pill.less
  src/less/pill/ds4/pill.less
  src/less/pill/ds6/pill.less
  src/less/variables/ds4/button-variables.less
  src/less/variables/ds6/button-variables.less
Labels: blocking: yes, module: pill, squash: yes please

#716 Switched colors for secondary disabled
  dist/button/ds6/button.css
  docs/static/ds6/skin.min.css
  src/less/button/ds6/button-primary.less
Labels: module: button

#718 LESS: mixins and variables cleanup/refactor (part 1)
  dist/less/ds4/mixins.less
  dist/less/ds6/mixins.less
  dist/less/mixins-common.less
  dist/less/variables-common.less
  docs/src/less/ds6/index.less
  docs/static/ds6/skin.min.css
  less.browser.json
  package.json
  src/less/less/ds4/mixins.less
  src/less/less/ds4/variables.less
  src/less/less/ds6/mixins.less
  src/less/less/ds6/variables.less
  src/less/mixins/typography/base/typography-mixins.less
  src/less/mixins/typography/ds4/typography-mixins.less
  src/less/mixins/typography/ds6/typography-mixins.less
  src/less/select/ds4/select.less
  src/less/select/ds6/select.less
  src/less/textbox/ds4/textbox-mixins.less
  src/less/textbox/ds4/textbox.less
  src/less/textbox/ds6/textbox-mixins.less
  src/less/textbox/ds6/textbox.less
  src/less/typography/base/typography.less
  src/less/typography/ds4/typography.less
  src/less/typography/ds6/typography.less
  src/less/variables/ds4/color-variables.less
  src/less/variables/ds4/typography-variables.less
  src/less/variables/ds6/color-variables.less
  src/less/variables/ds6/typography-variables.less
Labels: blocking: yes

#723 Color: updated grey colour palette
  dist/actionable/ds6/actionable.css
  dist/breadcrumb/ds6/breadcrumb.css
  dist/button/ds6/button.css
  dist/carousel/ds6/carousel.css
  dist/combobox/ds6/combobox.css
  dist/label/ds6/label.css
  dist/listbox-button/ds6/listbox-button.css
  dist/listbox/ds6/listbox.css
  dist/menu-button/ds6/menu-button.css
  dist/menu/ds6/menu.css
  dist/pill/ds6/pill.css
  dist/select/ds6/select.css
  dist/switch/ds6/switch.css
  dist/tab/ds6/tab.css
  dist/textbox/ds6/textbox.css
  dist/typography/ds6/typography.css
  docs/_includes/ds6/less-custom.html
  docs/src/less/ds6/index.less
  docs/static/ds6/docs.min.css
  docs/static/ds6/skin.min.css
  src/less/actionable/ds6/actionable.less
  src/less/breadcrumb/ds6/breadcrumb.less
  src/less/carousel/ds6/carousel.less
  src/less/label/ds6/label.less
  src/less/less/variables-common.less
  src/less/select/ds6/select.less
  src/less/switch/base/switch.less
  src/less/switch/ds6/switch.less
  src/less/tab/ds6/tab.less
  src/less/textbox/ds6/textbox.less
  src/less/variables/ds6/button-variables.less
  src/less/variables/ds6/color-variables.less
  src/less/variables/ds6/dropdown-variables.less
Labels: blocking: yes, squash: yes please

#728 Button: separated expand-button to own module (#679)
  dist/button/ds4/button.css
  dist/button/ds6/button.css
  dist/expand-button/ds4/expand-button.css
  dist/expand-button/ds6/expand-button.css
  docs/_includes/common/button.html
  docs/_includes/common/expand-button.html
  docs/_includes/common/install.html
  docs/_layouts/ds4/default.html
  docs/_layouts/ds6/default.html
  docs/ds6/index.html
  docs/index.html
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  expand-button.browser.json
  expand-button.less
  expand-button[skin-ds6].less
  gulpfile.js
  src/less/bundles/skin/ds4/skin.less
  src/less/bundles/skin/ds6/skin.less
  src/less/button/base/button-primary.less
  src/less/button/base/button-regular.less
  src/less/button/base/button-secondary.less
  src/less/button/base/button.less
  src/less/button/ds4/button-primary.less
  src/less/button/ds4/button-regular.less
  src/less/button/ds4/button-secondary.less
  src/less/button/ds4/button-sizes.less
  src/less/button/ds4/button.less
  src/less/button/ds6/button-legacy.less
  src/less/button/ds6/button-primary.less
  src/less/button/ds6/button-regular.less
  src/less/button/ds6/button-secondary.less
  src/less/button/ds6/button-sizes.less
  src/less/button/ds6/button.less
  src/less/expand-button/base/expand-button.less
  src/less/expand-button/ds4/expand-button.less
  src/less/expand-button/ds6/expand-button.less
Labels: blocking: yes, squash: yes please

#729 Button/Notice: consolidated source files
  dist/button/ds4/button.css
  dist/button/ds6/button.css
  dist/tooltip/ds4/tooltip.css
  dist/tooltip/ds6/tooltip.css
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  gulpfile.js
  src/less/button/base/button-primary.less
  src/less/button/base/button-regular.less
  src/less/button/base/button-secondary.less
  src/less/button/base/button.less
  src/less/button/ds4/button-primary.less
  src/less/button/ds4/button-regular.less
  src/less/button/ds4/button-secondary.less
  src/less/button/ds4/button-sizes.less
  src/less/button/ds4/button.less
  src/less/button/ds6/button-legacy.less
  src/less/button/ds6/button-primary.less
  src/less/button/ds6/button-secondary.less
  src/less/button/ds6/button-sizes.less
  src/less/button/ds6/button.less
  src/less/mixins/bubble/ds4/bubble.less
  src/less/mixins/bubble/ds6/bubble.less
  src/less/notice/base/notice-flyout.less
  src/less/notice/base/notice-inline.less
  src/less/notice/base/notice-page.less
  src/less/notice/base/notice.less
  src/less/notice/ds4/notice-flyout.less
  src/less/notice/ds4/notice-inline.less
  src/less/notice/ds4/notice-page.less
  src/less/notice/ds4/notice.less
  src/less/notice/ds6/notice-flyout.less
  src/less/notice/ds6/notice-inline.less
  src/less/notice/ds6/notice-page.less
  src/less/notice/ds6/notice.less
Labels: blocking: yes, squash: yes please

#732 Fixed listbox and menu to load expand-button
  listbox-button.browser.json
  listbox-button.less
  listbox-button[skin-ds6].less
  menu-button.browser.json
  menu-button.less
  menu-button[skin-ds6].less
Labels: blocked: dependency, blocking: yes, module: listbox

#735 Fix for unchecked color in DS6
  dist/checkbox/ds4/checkbox.css
  dist/checkbox/ds6/checkbox.css
  dist/icon/background/ds6/background.css
  dist/less/ds6/variables.less
  dist/svg/ds6/icons.svg
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin-base64.min.css
  docs/static/ds6/skin.min.css
  src/less/checkbox/base/checkbox.less
  src/less/checkbox/ds4/checkbox.less
  src/less/checkbox/ds6/checkbox.less
  src/less/less/ds6/variables.less
  src/svg/ds6/icons.svg
Labels: module: checkbox, semver: patch, squash: no thanks
