Repository eBay/skin, pull requests merged in 2020-06, with the labels that each got.

#1127 Updated toast__title to also include h2
  dist/toast/ds4/toast.css
  dist/toast/ds6/toast.css
  src/less/toast/base/toast.less
Labels: squash: yes please

#1126 Reorganized custom properties into separate folder
  dist/badge/ds4/badge.css
  dist/badge/ds6/badge.css
  dist/checkbox/ds4/checkbox.css
  dist/checkbox/ds6/checkbox.css
  dist/radio/ds4/radio.css
  dist/radio/ds6/radio.css
  dist/variables/base/filter-button-variables.less
  dist/variables/base/tooltip-variables.less
  dist/variables/ds4/typography-variables.less
  dist/variables/ds6/typography-variables.less
  gulpfile.js
  src/less/actionable/base/actionable.less
  src/less/actionable/ds4/actionable.less
  src/less/actionable/ds6/actionable.less
  src/less/badge/base/badge.less
  src/less/badge/ds4/badge.less
  src/less/badge/ds6/badge.less
  src/less/breadcrumbs/base/breadcrumbs.less
  src/less/breadcrumbs/ds4/breadcrumbs.less
  src/less/breadcrumbs/ds6/breadcrumbs.less
  src/less/checkbox/base/checkbox.less
  src/less/checkbox/ds4/checkbox.less
  src/less/checkbox/ds6/checkbox.less
  src/less/properties/ds4/actionable-properties.less
  src/less/properties/ds4/badge-properties.less
  src/less/properties/ds4/breadcrumbs-properties.less
  src/less/properties/ds4/checkbox-properties.less
  src/less/properties/ds4/radio-properties.less
  src/less/properties/ds4/switch-properties.less
  src/less/properties/ds6/actionable-properties.less
  src/less/properties/ds6/badge-properties.less
  src/less/properties/ds6/breadcrumbs-properties.less
  src/less/properties/ds6/checkbox-properties.less
  src/less/properties/ds6/radio-properties.less
  src/less/properties/ds6/switch-properties.less
  src/less/radio/base/radio.less
  src/less/radio/ds4/radio.less
  src/less/radio/ds6/radio.less
  src/less/switch/base/switch.less
  src/less/switch/ds4/switch.less
  src/less/switch/ds6/switch.less
  src/less/variables/ds4/typography-variables.less
  src/less/variables/ds6/typography-variables.less
Labels: squash: yes please

#1131 Document variables usage #1072
  CONTRIBUTING.md
Labels: squash: yes please

#1146 Added 4 new photo-editor icons
  dist/icon/ds6/icon.css
  dist/svg/ds6/icons.svg
  dist/variables/ds6/icon-variables.less
  docs/_includes/common/icon.html
  docs/_includes/ds6/symbols.html
  docs/test/icon/ds6/index.html
  src/less/icon/ds6/icon.less
  src/less/variables/ds6/icon-variables.less
  src/svg/ds6/icons.svg
Labels: module: icon

#1158 Filter Menu: add single select variant
  dist/filter-menu-button/ds4/filter-menu-button.css
  dist/filter-menu-button/ds6/filter-menu-button.css
  dist/filter-menu/ds4/filter-menu.css
  dist/filter-menu/ds6/filter-menu.css
  dist/variables/ds4/filter-menu-variables.less
  dist/variables/ds6/filter-menu-variables.less
  docs/_includes/common/filter-menu-button.html
  docs/_includes/common/filter-menu.html
  docs/_includes/common/menu-button.html
  docs/_includes/common/menu.html
  docs/src/js/base/menu.js
  docs/static/ds4/docs.min.js
  docs/static/ds6/docs.min.js
  src/less/filter-menu-button/base/filter-menu-button.less
  src/less/filter-menu/base/filter-menu.less
  src/less/variables/ds4/filter-menu-variables.less
  src/less/variables/ds6/filter-menu-variables.less
Labels: module: filter menu, module: filter menu button
