Repository eBay/skin, pull requests merged in 2020-03, with the labels that each got.

#1025 feat: combobox with actionable icon
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  docs/_includes/common/combobox.html
  src/less/combobox/base/combobox.less
  src/less/combobox/combobox.stories.js
Labels: squash: yes please

#1049 Fixed filter button cell to have pointer-events of none
  dist/filter-button/ds4/filter-button.css
  dist/filter-button/ds6/filter-button.css
  dist/mixins/filter-button/base/filter-button-mixins.less
  docs/static/ds4/skin.min.css
  docs/static/ds6/skin.min.css
  src/less/mixins/filter-button/base/filter-button-mixins.less
Labels: module: filter button

#1047 Added new icons for ds6.5
  dist/icon/ds6/icon.css
  dist/svg/ds6/icons.svg
  dist/variables/ds6/icon-variables.less
  docs/_includes/common/icon.html
  docs/_includes/ds6/symbols.html
  scripts/image-config.json
  scripts/import-svgs.js
  src/less/icon/ds6/icon.less
  src/less/variables/ds6/icon-variables.less
  src/svg/ds6/icons.svg
Labels: module: icon, squash: yes please

#1053 Website: use accessible pygments highlighter
  dist/typography/ds6/typography.css
  docs/src/less/base/pygments.less
  docs/static/ds4/docs.min.css
  docs/static/ds6/docs.min.css
  src/less/typography/ds6/typography.less
Labels: squash: no thanks

#1050 Integrate percy-storybook #1004
  docs/storybook/iframe.html
  docs/storybook/index.html
  docs/storybook/main.34a16217c8c8fad15810.bundle.js.map
  docs/storybook/main.846233f50cd7a1ac7541.bundle.js
  docs/storybook/main.846233f50cd7a1ac7541.bundle.js.map
  docs/storybook/runtime~main.34a16217c8c8fad15810.bundle.js.map
  docs/storybook/runtime~main.846233f50cd7a1ac7541.bundle.js
  docs/storybook/runtime~main.846233f50cd7a1ac7541.bundle.js.map
  docs/storybook/vendors~main.1fe11a144fff77cd81f5.bundle.js
  docs/storybook/vendors~main.34a16217c8c8fad15810.bundle.js.map
  docs/storybook/vendors~main.846233f50cd7a1ac7541.bundle.js
  docs/storybook/vendors~main.846233f50cd7a1ac7541.bundle.js.LICENSE.txt
  docs/storybook/vendors~main.846233f50cd7a1ac7541.bundle.js.map
  docs/storybook/vendors~main.f3e9a04d2b75cbfff077.bundle.js
  package.json
  scripts/cibuild
  yarn.lock
Labels: squash: yes please

#1024 Raveena/wizard stepper list
  dist/svg/ds4/icons.svg
  dist/svg/ds6/icons.svg
  dist/wizard-stepper/ds4/wizard-stepper.css
  dist/wizard-stepper/ds6/wizard-stepper.css
  docs/_includes/common/main.html
  docs/_includes/common/module-list.html
  docs/_includes/common/wizard-stepper.html
  docs/_includes/ds4/symbols.html
  docs/_includes/ds6/symbols.html
  docs/index.html
  docs/src/less/base/index.less
  docs/static/ds4/docs.min.css
  docs/static/ds6/docs.min.css
  index.browser.json
  index.less
  src/less/bundles/skin/ds4/skin.less
  src/less/bundles/skin/ds6/skin.less
  src/less/wizard-stepper/base/wizard-stepper.less
  src/less/wizard-stepper/ds4/wizard-stepper.less
  src/less/wizard-stepper/ds6/wizard-stepper.less
  src/less/wizard-stepper/wizard-stepper.stories.js
  src/svg/ds4/icons.svg
  src/svg/ds6/icons.svg
  wizard-stepper.less
  wizard-stepper[ds-4].less
Labels: squash: yes please

#1060 Fix RTL for combobox
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  docs/_includes/common/combobox.html
  docs/_includes/tests/combobox.html
  src/less/combobox/base/combobox.less
  src/less/combobox/combobox.stories.js
Labels: squash: yes please

#1064 Refactor wizard-stepper markup #191
  dist/wizard-stepper/ds4/wizard-stepper.css
  dist/wizard-stepper/ds6/wizard-stepper.css
  docs/_includes/common/wizard-stepper.html
  src/less/wizard-stepper/base/wizard-stepper.less
  src/less/wizard-stepper/wizard-stepper.stories.js
Labels: squash: yes please
