Repository eBay/skin, pull requests merged in 2020-02, with the labels that each got.

#1016 Fixed combobox readonly and badge width on menu
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  dist/menu-button/ds4/menu-button.css
  dist/menu-button/ds6/menu-button.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  src/less/combobox/base/combobox.less
  src/less/menu-button/base/menu-button.less
  src/less/menu/base/menu.less
Labels: squash: no thanks

#1018 Added color disabled for combobox
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  src/less/combobox/base/combobox.less
  src/less/combobox/ds4/combobox.less
  src/less/combobox/ds6/combobox.less
Labels: module: combobox

#1021 Fixed position of tick element and removed dropdown status
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  docs/_includes/common/combobox.html
  src/less/combobox/base/combobox.less
Labels: module: combobox

#1022 Fixed z-index for menu
  dist/combobox/ds4/combobox.css
  dist/combobox/ds6/combobox.css
  dist/listbox-button/ds4/listbox-button.css
  dist/listbox-button/ds6/listbox-button.css
  dist/menu-button/ds4/menu-button.css
  dist/menu-button/ds6/menu-button.css
  dist/mixins/dropdown/base/dropdown-mixins.less
  src/less/mixins/dropdown/base/dropdown-mixins.less
Labels: module: menu

#1029 Checkbox and Radio: update svg #1026
  dist/checkbox/ds4/checkbox.css
  dist/icon/ds6/icon.css
  dist/radio/ds4/radio.css
  dist/svg/ds4/icons.svg
  dist/svg/ds6/icons.svg
  dist/variables/ds6/icon-variables.less
  docs/_includes/common/checkbox.html
  docs/_includes/common/icon.html
  docs/_includes/common/radio.html
  docs/_includes/ds4/symbols.html
  docs/_includes/ds6/symbols.html
  docs/src/less/base/index.less
  docs/static/ds4/docs.min.css
  docs/static/ds6/docs.min.css
  src/less/checkbox/ds4/checkbox.less
  src/less/checkbox/ds6/checkbox.less
  src/less/radio/ds4/radio.less
  src/less/radio/ds6/radio.less
  src/less/variables/ds6/icon-variables.less
  src/svg/ds4/icons.svg
  src/svg/ds6/icons.svg
Labels: squash: yes please

#1038 Fix spinner path & GH Less paths
  dist/spinner/ds4/spinner.css
  dist/spinner/ds6/spinner.css
  gh.browser.json
  src/less/gh/ds6/gh-mixins.less
  src/less/spinner/ds4/spinner.less
  src/less/spinner/ds6/spinner.less
Labels: squash: no thanks

#1041 Checkbox & Radio: deprecate old small styles
  dist/icon/ds6/icon.css
  dist/svg/ds4/icons.svg
  dist/svg/ds6/icons.svg
  dist/variables/ds6/icon-variables.less
  docs/_includes/common/icon.html
  docs/_includes/ds4/symbols.html
  docs/_includes/ds6/symbols.html
  src/less/variables/ds6/icon-variables.less
  src/svg/ds4/icons.svg
  src/svg/ds6/icons.svg
Labels: squash: yes please

#1042 Merge back to master for 10.1.0 release
  dist/checkbox/ds4/checkbox.css
  dist/icon/ds6/icon.css
  dist/menu-button/ds4/menu-button.css
  dist/menu-button/ds6/menu-button.css
  dist/menu/ds4/menu.css
  dist/menu/ds6/menu.css
  dist/mixins/typography/base/typography-mixins.less
  dist/radio/ds4/radio.css
  dist/spinner/ds4/spinner.css
  dist/spinner/ds6/spinner.css
  dist/svg/ds4/icons.svg
  dist/svg/ds6/icons.svg
  dist/variables/ds6/icon-variables.less
  docs/_includes/common/checkbox.html
  docs/_includes/common/icon.html
  docs/_includes/common/menu-button.html
  docs/_includes/common/menu.html
  docs/_includes/common/radio.html
  docs/_includes/ds4/symbols.html
  docs/_includes/ds6/symbols.html
  docs/ds4/index.html
  docs/index.html
  docs/src/less/base/index.less
  docs/static/ds4/docs.min.css
  docs/static/ds4/docs.min.js
  docs/static/ds6/docs.min.css
  docs/static/ds6/docs.min.js
  docs/storybook/iframe.html
  docs/storybook/index.html
  docs/storybook/main.5a4746764487bcf475aa.bundle.js
  docs/storybook/main.5a4746764487bcf475aa.bundle.js.map
  docs/storybook/main.87b9a21f4e302528d8e0.bundle.js
  docs/storybook/main.87b9a21f4e302528d8e0.bundle.js.map
  docs/storybook/runtime~main.5a4746764487bcf475aa.bundle.js
  docs/storybook/runtime~main.5a4746764487bcf475aa.bundle.js.map
  docs/storybook/runtime~main.87b9a21f4e302528d8e0.bundle.js.map
  docs/storybook/vendors~main.1fe11a144fff77cd81f5.bundle.js
  docs/storybook/vendors~main.5a4746764487bcf475aa.bundle.js
  docs/storybook/vendors~main.5a4746764487bcf475aa.bundle.js.LICENSE.txt
  docs/storybook/vendors~main.5a4746764487bcf475aa.bundle.js.map
  docs/storybook/vendors~main.87b9a21f4e302528d8e0.bundle.js.map
  docs/storybook/vendors~main.f3e9a04d2b75cbfff077.bundle.js
  gh.browser.json
  package.json
  src/less/checkbox/ds4/checkbox.less
  src/less/checkbox/ds6/checkbox.less
  src/less/gh/ds6/gh-mixins.less
  src/less/menu-button/base/menu-button.less
  src/less/menu-button/menu-button.stories.js
  src/less/menu/base/menu.less
  src/less/menu/menu.stories.js
  src/less/mixins/typography/base/typography-mixins.less
  src/less/radio/ds4/radio.less
  src/less/radio/ds6/radio.less
  src/less/spinner/ds4/spinner.less
  src/less/spinner/ds6/spinner.less
  src/less/variables/ds6/icon-variables.less
  src/svg/ds4/icons.svg
  src/svg/ds6/icons.svg
Labels: squash: no thanks
